// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: api/helloworld/helloworld_errors.proto

package helloworld

import (
	_ "github.com/devil-dwj/wms/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloErrorCode int32

const (
	SayHelloErrorCode_OK       SayHelloErrorCode = 0
	SayHelloErrorCode_NOT_FIND SayHelloErrorCode = 1
	SayHelloErrorCode_NOT_NIL  SayHelloErrorCode = 2
)

// Enum value maps for SayHelloErrorCode.
var (
	SayHelloErrorCode_name = map[int32]string{
		0: "OK",
		1: "NOT_FIND",
		2: "NOT_NIL",
	}
	SayHelloErrorCode_value = map[string]int32{
		"OK":       0,
		"NOT_FIND": 1,
		"NOT_NIL":  2,
	}
)

func (x SayHelloErrorCode) Enum() *SayHelloErrorCode {
	p := new(SayHelloErrorCode)
	*p = x
	return p
}

func (x SayHelloErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SayHelloErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_helloworld_helloworld_errors_proto_enumTypes[0].Descriptor()
}

func (SayHelloErrorCode) Type() protoreflect.EnumType {
	return &file_api_helloworld_helloworld_errors_proto_enumTypes[0]
}

func (x SayHelloErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SayHelloErrorCode.Descriptor instead.
func (SayHelloErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_helloworld_helloworld_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_helloworld_helloworld_errors_proto protoreflect.FileDescriptor

var file_api_helloworld_helloworld_errors_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x1f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x44, 0x0a, 0x11, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x49,
	0x4e, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x5f, 0x4e, 0x49, 0x4c, 0x10,
	0x02, 0x1a, 0x05, 0x88, 0xf1, 0x04, 0xf4, 0x03, 0x1a, 0x05, 0x80, 0xf1, 0x04, 0x90, 0x03, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x6c, 0x2d, 0x64, 0x77, 0x6a, 0x2f, 0x77, 0x6d, 0x73, 0x2d, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_helloworld_helloworld_errors_proto_rawDescOnce sync.Once
	file_api_helloworld_helloworld_errors_proto_rawDescData = file_api_helloworld_helloworld_errors_proto_rawDesc
)

func file_api_helloworld_helloworld_errors_proto_rawDescGZIP() []byte {
	file_api_helloworld_helloworld_errors_proto_rawDescOnce.Do(func() {
		file_api_helloworld_helloworld_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_helloworld_helloworld_errors_proto_rawDescData)
	})
	return file_api_helloworld_helloworld_errors_proto_rawDescData
}

var file_api_helloworld_helloworld_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_helloworld_helloworld_errors_proto_goTypes = []interface{}{
	(SayHelloErrorCode)(0), // 0: api.helloworld.SayHelloErrorCode
}
var file_api_helloworld_helloworld_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_helloworld_errors_proto_init() }
func file_api_helloworld_helloworld_errors_proto_init() {
	if File_api_helloworld_helloworld_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_helloworld_helloworld_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_helloworld_helloworld_errors_proto_goTypes,
		DependencyIndexes: file_api_helloworld_helloworld_errors_proto_depIdxs,
		EnumInfos:         file_api_helloworld_helloworld_errors_proto_enumTypes,
	}.Build()
	File_api_helloworld_helloworld_errors_proto = out.File
	file_api_helloworld_helloworld_errors_proto_rawDesc = nil
	file_api_helloworld_helloworld_errors_proto_goTypes = nil
	file_api_helloworld_helloworld_errors_proto_depIdxs = nil
}
