// Code generated by protoc-gen-go-router. DO NOT EDIT.
package helloworld

import (
	context "context"
	http "github.com/devil-dwj/wms/runtime/http"
)

type GreeterServerHandler interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterRouter(s http.ServiceRegistrar, srv GreeterServerHandler) {
	s.RegisterService(&GreeterRouter_Desc, srv)
}

func _GreeterRouter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor http.ServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServerHandler).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, h)
}

var GreeterRouter_Desc = http.RouterDesc{
	ServiceName: "helloworld.Greeter",
	Methods: []http.MethodDesc{
		{
			Name:    "SayHello",
			Method:  "GET",
			Path:    "/api/helloworld/SayHello",
			Handler: _GreeterRouter_SayHello_Handler,
		},
	},
}
