// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package helloworld

import (
	fmt "fmt"
	errors "github.com/devil-dwj/wms/errors"
)

func ErrorNotFind(format string, args ...interface{}) error {
	return errors.Errorf(400, int(SayHelloErrorCode_NOT_FIND), fmt.Sprintf(format, args...))
}

func ErrorNotNil(format string, args ...interface{}) error {
	return errors.Errorf(500, int(SayHelloErrorCode_NOT_NIL), fmt.Sprintf(format, args...))
}
